### ISSUE TITLE
Add line/column location of parse error to reporting 

### ISSUE THREAD

**Issue by sebrose** [cucumber-attic/bool#11]
Add the location of the error to the reporting mechanism to make it easier for the user to identify where the problem is.

**Comment by mattwynne** [comment]
Is this ticket for all platforms or just Ruby?

**Comment by aslakhellesoy** [comment]
I've labelled it with c/java/javascript, which should cover all platforms

**Comment by sebrose** [comment]
I've committed changes for Java and C/Ruby. I'll have a look at Javascript when I get a chance (but the tests all still pass)

**Comment by aslakhellesoy** [comment]
@sebrose it looks like you accidentally reverted a bunch of stuff I had done in 859dd0113d5be07dda3a0ca562b26d452676424a

Can you please read my comments in that commit and restore what was removed?

**Comment by sebrose** [comment]
Yes. Will do

**Comment by sebrose** [comment]
I have committed a fix to this in the fix_unwanted_revert branch. @aslakhellesoy could you have a quick look to check that it's OK & merge across to master?

**Comment by aslakhellesoy** [comment]
Thanks a lot Seb. Looks perfect. It's easy to uncock-up with Git too, once you figure out the command to use :-)

**Comment by sebrose** [comment]
Yes indeed. And there are plenty to choose from.

On 8 February 2013 07:41, Aslak Hellesøy notifications@github.com wrote:

> Thanks a lot Seb. Looks perfect. It's easy to uncock-up with Git too, once
> you figure out the command to use :-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cucumber/bool/issues/11#issuecomment-13280051.

## 

ACCU - Professionalism in Programming - http://accu.org

http://www.claysnow.co.uk
http://twitter.com/#!/sebrose
http://uk.linkedin.com/in/sebrose

**Comment by aslakhellesoy** [comment]
I have implemented this for JavaScript as well. I have only made some modifications to how we report line and column numbers. In addition to embedding them in the exception message we also attach them to the exceptions. This makes it easy for a Cucumber implementations to throw exceptions with a stack frame pointing to the file and line. It can also be helpful for other purposes, like outputting structured runtime exceptions such as a JSON document with attributes for the line and column numbers.

I'm a little stuck with C thouugh. In JFlex we just throw an exception, but I'm not sure how to do something equivalent with Flex. I don't like what I have done now, which is to return an `ERROR_TOKEN`, but maybe that is the way to go. I find it hard to find good docs about this. And moreover, the location values I get back with this code is wrong as well.

@sebrose or anyone else - do you have any idea how we can make this work with Flex/Bison in C?

**Comment by aslakhellesoy** [comment]
Forgot to say, my code is on the `syntax-error-line-column` branch: https://github.com/cucumber/bool/network

**Comment by aslakhellesoy** [comment]
This might be useful to fix the locations: https://github.com/remusao/Bison-Flex-C-template/blob/master/src/parse/scan.l

**Comment by aslakhellesoy** [comment]
And this is how we might deal with lexing errors: https://github.com/GrooveStomp/Flex-Bison/blob/master/samples/purecalc.l#L74

**Comment by sebrose** [comment]
I've pushed some changes in the syntax-error-line-column branch.

We get correct line & column number in C & report the invalid character. I added a basic test file as I went just to make life easier. It's not a great unit test framework, but it is simple!

The remaining problem is that JFlex seems to have different behaviour, in some cases, under Java and JRuby. I added a test to LexerTest.java that duplicates the "is raised on parse error" spec in parse_test.rb. What this seems to show is that Java/JFlex & Ruby/GNU-Flex return the same column number (end of input stream) as each other, but JRuby/JFlex returns column number + 1. Any ideas why?

**Comment by aslakhellesoy** [comment]
@sebrose are you referring to `test_again`? I removed that test in 5dd3ad4a34f77c1b1105bb4d020dfffd10241ee4 because it never entered the catch block because the text lexes just fine. It just doesn't parse, but that's irrelvant in this case since we're testing the lexer and not the parser.

**Comment by sebrose** [comment]
@aslakhellesoy Thanks for removing `test_again` - it was getting late : )

The problem I was struggling with can be seen in `parser_spec.rb` where the column number returned differs between Ruby & JRuby. We need to do something about this.

**Comment by aslakhellesoy** [comment]
I have created #17 for column number inconsistencies. I don't think it's the most important issue to solve right now. Line numbers should be sufficient to give us decent line numbers, at least for gherkin.

**Comment by aslakhellesoy** [comment]
testing
