### ISSUE TITLE
Inconsistent gcc build flags for C and Ruby

### ISSUE THREAD

**Issue by sebrose** [cucumber-attic/bool#13]
c/Makefile uses the following flags:
-fPIC -O2 -Werror -Wall -Wunused-parameter

The makefile generated during the Ruby build also includes -Wextra and then explicitly _turns off_ many of the unused options (implied by -Wextra), which we then turn on again using a further -Wall

We should:
1) add -Wextra to c/Makefile
2) remove all instances of -Wunused-parameter (because this is implied by -Wextra)

This reduces unnecessary noise in the makefiles and makes the build consistent for C and Ruby

**Comment by aslakhellesoy** [comment]
I agree we should add `-Wextra` to `c/Makefile`, but I'm not so sure about removing `-Wunused-parameter` from `ruby/ext/bool_ext/extconf.rb`. The generated `Makefile` contains (amon other things) `-Wextra -Wno-unused-parameter`.

It doesn't seem like our `-Wall` implicitly turns `-Wunused-parameter` back on. Try commenting out the `UNUSED(klass);` in `ext.c`. You'll only get a warning (and fail the build) if we explicitly specify `-Wunused-parameter`.

**Comment by sebrose** [comment]
@aslakhellesoy I commented out the UNUSED(klass) statement in ext.c and the -Wunused-parameter from extconf.rb and still got the warning as expected. Could you try yours again please?

**Comment by sebrose** [comment]
@aslakhellesoy this may be the clang/gcc issue back again. The problem with using `-Wunused-parameter` is that there are several other warning flags explicitly fiddled with in the generated makefile. 

`-Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration`

For consistency we either need to find a way to stop the generated makefile from fiddling with them, or we should to include them all in the C makefile.
