### ISSUE TITLE
Release karma request

### ISSUE THREAD

**Issue by sebrose** [cucumber-attic/bool#18]
I have created accounts on the 3 sites. All have the same username: sebrose

Still waiting for publish rights at Sonatype

Can I have release karma?

**Comment by aslakhellesoy** [comment]
I have given you npm karma. I need the email you registered with at rubygems.org to give you karma there. See af3912f5852739689c67fd40c3e5c3394ddc6f2d

**Comment by sebrose** [comment]
github@claysnow.co.uk

**Comment by aslakhellesoy** [comment]
Done! http://rubygems.org/gems/bool
