### ISSUE TITLE
Release Karma Request

### ISSUE THREAD

**Issue by ilanpillemer** [cucumber-attic/bool#20]
rubygems.org : ilanpillemer
npmjs.org : ilanpillemer
oss.sonatype.org : ilanpillemer

All three have the same username (same as in github too) : ilanpillemer
email: ilan.pillemer@gmail.com

I have submitted the following issue to Sonatype: https://issues.sonatype.org/browse/OSSRH-5382
Can someone confirm this was correctly filled in?

**Comment by aslakhellesoy** [comment]
@ilanpillemer DEVELOPERS.md links to an old issue you're supposed to comment in. It might be quicker if you comment in that one.

@sebrose can you give the karma?

**Comment by ilanpillemer** [comment]
hmm.. Joel Orlina has already added this comment to the issue(https://issues.sonatype.org/browse/OSSRH-5382): "Can you have Aslak Hellesøy, the Cucumber project owner, comment on this issue to confirm that you should receive deployer access to this groupId?"... so maybe just add a comment?

I can't see a link to an issue in DEVELOPERS.md in BOOL? Are you referring to a different DEVELOPERS.md?

**Comment by ilanpillemer** [comment]
Joel has closed the Sonatype issue, saying he has granted permissions based on Aslak's comment in this issue #20.

**Comment by aslakhellesoy** [comment]
@ilanpillemer My bad about the link. Fixed! 45b3c6a8d3751a8c1a062736885cf4a6a0d8eaee

**Comment by ilanpillemer** [comment]
@sebrose have you had a chance to give the karma yet?

**Comment by aslakhellesoy** [comment]
I've done this now
