### ISSUE TITLE
Release Karma Request

### ISSUE THREAD

**Issue by dkowis** [cucumber-attic/bool#23]
- Rubygems: https://rubygems.org/profiles/BeepDog
- nerd.js: username: beepdog (aww, there's no profile link)
- Sonatype: https://issues.sonatype.org/browse/OSSRH-2050?focusedCommentId=180294&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-180294
  - username: beepdog

I don't believe Sonatype has authorized me for anything, their instructions are also a bit confusing, I think I'm supposed to comment on the ticket used to create your repo... but I'm not completely sure.

So this issue might be a bit premature, just waiting on Sonatype.

**Comment by aslakhellesoy** [comment]
Assigning this to you @mattwynne so you get the hang of it.

**Comment by dkowis** [comment]
Sonatype has added me to things, btw

**Comment by mattwynne** [comment]
@beepdog you should have the karma now. I am still making point releases myself to iron out the kinks in my own setup, so be warned if you try to do your own releases.

**Comment by mattwynne** [comment]
Okay I am done. 1.0.9 is all yours @beepdog. Good luck and RTFM is all I can say.

**Comment by aslakhellesoy** [comment]
Can we close this ticket or are we still waiting for @dkowis to confirm?

**Comment by dkowis** [comment]
I lost the email in all the other noise, sorry :( . I'll do this this weekend.

**Comment by dkowis** [comment]
Aside: is there a way to get github to assign @beepdog to me? heh.

**Comment by dkowis** [comment]
#37 is resolved for me. I'll try to go through the release process tonight or tomorrow (probably tomorrow [Friday])

**Comment by dkowis** [comment]
Woo hoo! I've released 1.0.14 after only 3 tries, heh.

**Comment by aslakhellesoy** [comment]
Awesome! I think we're enough people who know how to release this beast now :8ball:
