### ISSUE TITLE
Fail c build if there are warnings

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber-attic/bool#3]
There is currently one warning with `clang` on travis:

https://travis-ci.org/cucumber/bool/jobs/4527724

**Comment by aslakhellesoy** [comment]
In Ruby, `rake cross compile` als gives several warnings:

```
compiling ../../../../ext/bool_ext/ast.c
compiling ../../../../ext/bool_ext/ext.c
../../../../ext/bool_ext/ext.c: In function ‘Init_bool_ext’:
../../../../ext/bool_ext/ext.c:48:5: warning: ISO C90 forbids mixed declarations and code
compiling ../../../../ext/bool_ext/lexer.c
lexer.c:1133:17: warning: ‘yyunput’ defined but not used
lexer.c:1175:16: warning: ‘input’ defined but not used
compiling ../../../../ext/bool_ext/parser.c
linking shared-object bool_ext.so
cd -
install -c tmp/x86-mingw32/bool_ext/1.9.3/bool_ext.so lib/bool_ext.so
```

**Comment by aslakhellesoy** [comment]
Turns out we need Bison 2.7 in order for all warnings to go away. If you're using Bison 2.5 (which is what's on travis, and also the latest you get with apt-get), then you get warnings.

So we need to force Bison 2.7. I'll add a target to the Makefile that installs it.

**Comment by aslakhellesoy** [comment]
The toplevel `Makefile` now installs and uses `./bison-2.7` if bison is absent or older than 2.7. All warnings are gone now, except for mingw compilation. We can live with that - it's based on an old gcc and I don't think it's a big issue as long as the main gcc/clang build is warning-less.

**Comment by ilanpillemer** [comment]
The Java README still refers to needing bison 2.5; should that be updated to 2.7?

**Comment by aslakhellesoy** [comment]
Yes please!
