### ISSUE TITLE
Release Karma Request

### ISSUE THREAD

**Issue by paoloambrosio** [cucumber-attic/bool#49]
User on Sonatype, RubyGems and NpmJs: paoloambrosio

Commented on Sonatype OSSRH-2050 (hope it's the right one)

**Comment by aslakhellesoy** [comment]
Thanks. For npm we also need to give you cucumber-HTML karma. I'm w/o laptop for a week or so, so great if someone else can look into this. I think @jbpros might be the only other person with cucumber-HTML npm karma.

We also need to move the karma docs/tickets to the website repo - it's a cross project thing.

**Comment by paoloambrosio** [comment]
Any update on this?

**Comment by aslakhellesoy** [comment]
Done! Let me know if you need more.

Aslak
